window.HQSetupReady=(async function(){
await window.HQCloud.ready;
'use strict';
const KEY='friendhq:settings:v1';
try{window.HQSettings=JSON.parse(HQStore.getItem(KEY))||{};}catch(e){window.HQSettings={};}
window.HQCompanyName=()=> (window.HQSettings.name||'Your')+' INC';
function sheet(value){if(!value.trim())return {id:'',gid:'0'};let u;try{u=new URL(value);}catch(e){throw Error('Paste the full Google Sheets link.');}const m=u.pathname.match(/^\/spreadsheets\/d\/([\w-]+)/);if(u.hostname!=='docs.google.com'||!m)throw Error('Use a Google Sheets link, not a job posting link.');const gid=new URLSearchParams(u.hash.slice(1)).get('gid')||u.searchParams.get('gid')||'0';if(!/^\d+$/.test(gid))throw Error('The sheet tab ID must be a number.');return {id:m[1],gid};}
window.openHQSetup=function(){
let dialog=document.getElementById('hqSetup');if(dialog){dialog.showModal();return;}
dialog=document.createElement('dialog');dialog.id='hqSetup';dialog.innerHTML=`
<form id="hqSettingsForm"><h2>Your own little company</h2><p>Plan your day, finish tasks, and build an igloo with your penguin team.</p>
<label>Company name <span>(we add INC)</span><input id="hqName" required maxlength="32" placeholder="e.g. Luna" autocomplete="organization"></label>
<p class="hq-note">Use Email sign-in for an account, or continue in browser-only mode. Check the save status above your office. Account & backup includes full downloads and saved versions. Email delivery is currently limited to the project owner while the sending service is being set up. Installing the app uses the generic name “My HQ”; your company name appears inside the app and browser tab.</p>
<details><summary>Customize your departments</summary><p>Rename the six rooms around your own goals. Tasks and history stay with their room. Connected job trackers still feed the first room.</p><div id="hqDepartments"></div></details>
<label><input id="hqJobMode" type="checkbox" style="display:inline;width:auto"> Job search mode — show the job pipeline and connect a tracker</label>
<details><summary>Connect your job tracker (optional)</summary>
<ol><li><a href="job-tracker.csv" download>Download the blank job tracker</a>, then import it into a new Google Sheet.</li><li>Keep the column headings. Give every role a unique, permanent Role ID. Put the actual job-posting URL in Application Link.</li><li>Use <strong>Prospecting</strong> for roles you have not applied to. After submitting, set Round Status to <strong>Applied</strong> and Date Applied to the real submission date. Later supported statuses: Screening Interview, First Round Interview, Second Round Interview, Final Round Interview, Rejected, Offer, No Reply.</li><li>For automatic reading, the sheet must be viewable without signing in (Share → Anyone with the link → Viewer). Anyone with that link can read it. Use a separate sheet without private notes or contact details. If you prefer to keep it private, leave this disconnected and add tasks manually.</li><li>Open the correct sheet tab, copy its full address, and paste it below.</li></ol>
<label>Job tracker link<input id="hqSheet" type="url" placeholder="https://docs.google.com/spreadsheets/d/…/edit#gid=0"></label>
<p>Planning or rescheduling here does not edit your sheet. Refresh tracker reads changes. Historical submissions from before your first connection are not backfilled as completed tasks. A submission needs both a supported status and a valid Date Applied.</p></details>
<details><summary>Outreach tracker (optional)</summary>
<p>Optional sheet: <a href="outreach-tracker.csv" download>download the outreach headings</a>. Use Name, Company, Date Reached Out and Date Replied. The same public-view access requirement applies; avoid private contact information. Dates must be actual event dates.</p>
<label>Optional outreach sheet link<input id="hqOutreach" type="url"></label><label>Outreach tab name<input id="hqOutreachTab" placeholder="Outreach Tracker"></label></details>
<details><summary>How to use your HQ</summary><ol><li>Open Goals and choose outcomes that matter to you.</li><li>Use Plan this week to set weekly outcomes; Add tasks to schedule small steps.</li><li>Complete today's tasks to build today's igloo. Adding unfinished work reopens it.</li><li>Review your day and week. The calendar keeps your daily history.</li></ol><p>Calendar planning is built in. Google Calendar account sync and automatic LinkedIn monitoring are not included. Optional browser reminders require permission and depend on the app/browser being available.</p></details>
<details><summary>Prompts to copy into your assistant</summary>
<label>Plan my week<textarea readonly rows="4">Help me plan a realistic week. Ask for my fixed appointments, available time, deadlines and three important outcomes. Break each outcome into small tasks with a date, duration and category: Job Hunt, Family & Friends, L&D, Content Building, Life Admin or Health. Do not invent appointments or mark work complete.</textarea></label>
<label>Prepare job tracker rows<textarea readonly rows="4">Help me organize these job links into rows with: Role ID, Company, Role, Round Status, Date Applied, Application Link, Location, Notes. Use a stable unique Role ID and the actual posting URL. Mark unsubmitted roles Prospecting and leave Date Applied blank. Never infer that I applied. Ask about missing details.</textarea></label>
</details>
<p id="hqSetupError" role="alert"></p><div class="hq-actions"><button type="submit">Save & open my office</button><button type="button" id="hqCancel">Close</button></div></form>`;
const style=document.createElement('style');style.textContent='#hqSetup{width:min(660px,calc(100vw - 32px));max-height:85vh;box-sizing:border-box;border:3px solid #9dcfee;border-radius:20px;padding:26px;color:#23334b;background:#f4faff;font:16px/1.5 system-ui;overflow:auto}#hqSetup::backdrop{background:#172f49aa}#hqSetup h2{margin-top:0}#hqSetup label{display:block;margin:16px 0;font-weight:600}#hqSetup input,#hqSetup textarea{display:block;width:100%;box-sizing:border-box;font:inherit;border:1px solid #86b9d8;border-radius:8px;padding:10px;background:white;color:#23334b}#hqSetup details{padding:14px 0;border-top:1px solid #bdd9eb}#hqSetup summary{cursor:pointer;font-weight:700}#hqSetup a{color:#12618b}#hqSetup .hq-note{font-size:14px}#hqSetup button{font:inherit;padding:10px 15px;border:1px solid #2b827c;border-radius:8px;cursor:pointer;background:#d8f3ef}#hqSetup .hq-actions{display:flex;gap:10px;flex-wrap:wrap}#hqSetupError{color:#a12626}';document.head.append(style);document.body.append(dialog);
const cfg=window.HQSettings;
dialog.querySelector('#hqJobMode').checked=cfg.jobMode===true||(!('jobMode' in cfg)&&!!cfg.sheetId);
const defaults=[['job','Job Hunt'],['learning','L&D'],['portfolio','Content Building'],['budget','Life Admin'],['health','Health'],['friends','Family & Friends']];
const departments=dialog.querySelector('#hqDepartments');
defaults.forEach(([id,label])=>{const saved=(cfg.departments||{})[id]||{};const box=document.createElement('fieldset');const legend=document.createElement('legend');legend.textContent=label+' room';box.append(legend);[['name','Department name',saved.name||label,40],['purpose','What is this department for?',saved.purpose||'',180]].forEach(([field,title,value,max])=>{const l=document.createElement('label');l.textContent=title;const input=document.createElement('input');input.id='dept-'+id+'-'+field;input.value=value;input.maxLength=max;input.required=field==='name';l.append(input);box.append(l);});departments.append(box);});
dialog.querySelector('#hqName').value=cfg.name||'';
dialog.querySelector('#hqSheet').value=cfg.sheetId?'https://docs.google.com/spreadsheets/d/'+cfg.sheetId+'/edit#gid='+cfg.gid:'';
dialog.querySelector('#hqOutreach').value=cfg.outreachId?'https://docs.google.com/spreadsheets/d/'+cfg.outreachId+'/edit':'';
dialog.querySelector('#hqOutreachTab').value=cfg.outreachTab||'Outreach Tracker';
dialog.querySelector('#hqCancel').onclick=()=>dialog.close();
dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const name=dialog.querySelector('#hqName').value.trim().replace(/\s+inc\.?$/i,'').trim();if(!name)throw Error('Choose a company name.');const jobs=sheet(dialog.querySelector('#hqSheet').value),outreach=sheet(dialog.querySelector('#hqOutreach').value);const departments={};defaults.forEach(([id])=>{const name=dialog.querySelector('#dept-'+id+'-name').value.trim(),purpose=dialog.querySelector('#dept-'+id+'-purpose').value.trim();if(!name)throw Error('Give every department a name.');if(/[<>]/.test(name+purpose))throw Error('Please use plain text for department names and descriptions.');departments[id]={name,purpose};});HQStore.setItem(KEY,JSON.stringify({jobMode:dialog.querySelector('#hqJobMode').checked,departments,name,sheetId:jobs.id,gid:jobs.gid,outreachId:outreach.id,outreachTab:dialog.querySelector('#hqOutreachTab').value.trim()||'Outreach Tracker'}));await window.HQCloud.sync();location.reload();}catch(err){dialog.querySelector('#hqSetupError').textContent=err.message;}};
dialog.showModal();
};
if(!window.HQSettings.name)window.openHQSetup();
})();

// Help stays separate from company settings and never changes saved progress.
window.HQSetupReady.then(function(){
  var style=document.createElement('style');style.textContent='#hqHelpButton{position:fixed;right:16px;bottom:max(16px,env(safe-area-inset-bottom));z-index:1000;border:2px solid #76b2d7;border-radius:24px;background:#fff;color:#23334b;padding:10px 16px;font:20px "VT323","Courier New",monospace;box-shadow:0 3px 12px #1233;cursor:pointer}body{padding-bottom:70px}#hqFAQ{width:min(620px,calc(100vw - 32px));max-height:85vh;box-sizing:border-box;overflow:auto;border:3px solid #9dcfee;border-radius:18px;padding:24px;background:#f4faff;color:#23334b;font:16px/1.55 system-ui}#hqFAQ::backdrop{background:#172f49aa}#hqFAQ summary{font-weight:650;cursor:pointer;padding:14px 0}#hqFAQ details{border-bottom:1px solid #bed9ea}#hqFAQ a{color:#12618b}#hqFAQ button{font:inherit;padding:8px 14px;border-radius:8px;cursor:pointer}#hqFAQ h2{margin-top:0}';document.head.append(style);
  var button=document.createElement('button');button.id='hqHelpButton';button.textContent='FAQ & help';button.setAttribute('aria-haspopup','dialog');document.body.append(button);
  var dialog=document.createElement('dialog');dialog.id='hqFAQ';dialog.setAttribute('aria-labelledby','hqFAQTitle');dialog.innerHTML=`<form method="dialog"><button style="float:right" aria-label="Close FAQ">Close</button></form><h2 id="hqFAQTitle">FAQ & help</h2>
<details open><summary>How do I install this as a desktop app?</summary><ol><li>Open this website in <strong>Google Chrome</strong> on your computer, using the same Chrome profile where you keep your progress.</li><li>Open Chrome’s three-dot menu → <strong>Cast, save, and share → Install page as app</strong>. You may also see an install icon in the address bar.</li><li>Confirm Install, then launch the app from your computer’s app launcher. It may be named <strong>My HQ</strong>.</li></ol><p>If the option is missing, check whether it is already installed and update Chrome. You can still use the website normally.</p><p>Installing gives you an app window. It does not add cloud backup or transfer data from another browser.</p><p><a href="https://support.google.com/chrome/answer/9658361" target="_blank" rel="noopener noreferrer">Google’s installation guide ↗</a></p></details>
<details><summary>Where is my progress saved?</summary><p>Browser-only mode saves on this device and profile. Signed-in mode saves to your private account; wait for “Saved to cloud” before closing. If saving fails, the app keeps a local copy and shows a warning. Email delivery is currently limited to the project owner until the email service is connected.</p><p>Signed-in users: open Account & backup to download a full copy or one of the last 50 saved versions. These versions are kept in the same database, not an independent disaster backup. Keep occasional downloaded copies. Downloads do not yet have a one-click restore; keep them for recovery assistance. More tools → Export JSON is a smaller snapshot.</p></details>
<details><summary>My tasks seem to have disappeared</summary><p>Check the selected date, open collapsed departments and completed-task lists, and make sure you are using the same browser profile and website address. The friends’ template and personal app have separate progress.</p><p>Do not clear site data or reset the browser to troubleshoot. If you previously saw “Saved to cloud”, sign in to the same account while online. Browser-only or unsynced changes cannot be recovered from the cloud. Keep any downloaded exports.</p></details>
<details><summary>The date or page is out of date</summary><p>Use <strong>Refresh today</strong> near the date. If needed, reload the page or close and reopen the app while online. Check your device’s date and timezone. Refreshing preserves saved progress; clearing site data does not.</p></details>
<details><summary>How do I change my company or departments?</summary><p>Open <strong>Settings</strong>. Change your company name or expand <strong>Customize your departments</strong> to rename the six rooms and describe their purpose. Save to apply. Existing tasks stay with their room.</p></details>
<details><summary>Where is the job pipeline? Why is it not syncing?</summary><p>Enable <strong>Job search mode</strong> in Settings, then follow Connect your job tracker. Use the full link to the correct Google Sheet tab and keep the downloaded template’s headings. The sheet must be readable without signing in; use a separate sheet without sensitive information.</p><p>Open Job pipeline and use <strong>Refresh tracker</strong>. Check your internet connection and any displayed error. Unsubmitted roles should be Prospecting. Only an explicitly submitted status with a valid Date Applied can create a dated submission task. Planning in HQ does not edit the sheet.</p></details>
<details><summary>Why is my igloo incomplete?</summary><p>Each completed task adds an equal share to that day’s igloo. Finish every task for the day to complete it. Adding another unfinished task reopens the igloo. A new calendar day starts a new igloo; past days remain in the calendar.</p></details>
<details><summary>Why did I not receive a reminder?</summary><p>Reminders need browser notification permission and the app to remain open, including in the background. Check your browser and system notification settings. They are not guaranteed when the app is closed.</p></details>
<details><summary>Something else is not working</summary><p>Note what you clicked, what you expected and what happened. Share that description, your browser/device, and a screenshot with the person who shared this app. Hide personal tasks, email addresses and tracker details before sharing.</p></details>`;document.body.append(dialog);button.addEventListener('click',function(){dialog.showModal();});dialog.addEventListener('close',function(){button.focus();});
});
